"""Upstream HTTP relay: byte-faithful forwarding with disconnect propagation."""

from __future__ import annotations

import asyncio
import logging

import aiohttp
from aiohttp import web

log = logging.getLogger(__name__)

# Hop-by-hop headers are connection-scoped and must not be relayed end to end
# (RFC 7230 6.1). Stripped in both directions.
_HOP_BY_HOP = frozenset(
    {
        "connection",
        "keep-alive",
        "proxy-authenticate",
        "proxy-authorization",
        "te",
        "trailer",
        "transfer-encoding",
        "upgrade",
    }
)

# Request headers regenerated by the client for the upstream hop.
_DROP_REQUEST = _HOP_BY_HOP | {"host", "content-length"}


class UpstreamProxy:
    """Relays requests to the LM Studio upstream, unbuffered and byte-faithful."""

    def __init__(self, session: aiohttp.ClientSession, upstream: str):
        self._session = session
        self._upstream = upstream.rstrip("/")

    async def forward(
        self,
        request: web.Request,
        upstream_path: str,
        body: bytes,
    ) -> web.StreamResponse:
        url = self._upstream + upstream_path
        headers = _filter_request_headers(request.headers)

        try:
            upstream_resp = await self._session.request(
                request.method,
                url,
                headers=headers,
                params=request.query.copy() if request.query_string else None,
                data=body or None,
            )
        except (aiohttp.ClientConnectorError, aiohttp.ServerConnectionError, asyncio.TimeoutError) as exc:
            log.warning("proxy: upstream connect failed for %s: %s", upstream_path, exc)
            return web.json_response({"error": "upstream unavailable"}, status=502)

        return await _relay(request, upstream_resp)

    async def probe_models(self, timeout: float = 5.0) -> bool:
        """Return True when the upstream answers /v1/models with any HTTP status.

        Any HTTP response (including 401/404) proves the upstream is reachable
        and alive. LM Studio returns 401 to unauthenticated /v1/models probes,
        and the daemon holds no secrets (D3), so demanding 200 would keep readyz
        permanently not-ready. Only a connect error or timeout means not ready.
        """
        try:
            async with self._session.get(
                self._upstream + "/v1/models",
                timeout=aiohttp.ClientTimeout(total=timeout),
            ):
                return True
        except Exception as exc:  # noqa: BLE001
            log.warning("proxy: /v1/models probe failed: %s", exc)
            return False


async def _relay(
    request: web.Request,
    upstream_resp: aiohttp.ClientResponse,
) -> web.StreamResponse:
    response = web.StreamResponse(
        status=upstream_resp.status,
        headers=_filter_response_headers(upstream_resp.headers),
    )
    # Status and headers are flushed here, before the first body chunk, and are
    # never buffered (streamed-header edge c). A non-200 upstream is relayed the
    # same way, status and body as-is (edge a).
    await response.prepare(request)

    try:
        async for chunk in upstream_resp.content.iter_any():
            await response.write(chunk)
    except (ConnectionResetError, asyncio.CancelledError):
        # Downstream client disconnected mid-stream. Abort the upstream request
        # rather than draining it (R7), then re-raise to unwind the handler.
        upstream_resp.close()
        raise
    except aiohttp.ClientError as exc:
        # Upstream died mid-stream. Close downstream with no synthesized [DONE]
        # (edge b); the truncated stream is the honest signal.
        log.warning("proxy: upstream stream error: %s", exc)
        upstream_resp.close()
        return response
    finally:
        upstream_resp.release()

    await response.write_eof()
    return response


def _filter_request_headers(headers) -> dict[str, str]:
    return {key: value for key, value in headers.items() if key.lower() not in _DROP_REQUEST}


def _filter_response_headers(headers) -> dict[str, str]:
    return {key: value for key, value in headers.items() if key.lower() not in _HOP_BY_HOP}
